In [32]:
import numpy as np
import pandas as pd

In [33]:
df=pd.read_csv("Uncleaned_Stock_Market_Dataset.csv")

In [34]:
df.head(10)

,Date,Index_Name,Country,Open,High,Low,Close,Volume,Daily_Change_Percent
0,2020-11-15,NASDAQ Composite,USA,11361.46,11934.64,11323.18,11797.26,47514127.0,3.84
1,2021-08-30,FTSE 100,UK,10298.33,10829.50,10194.32,10736.46,1471464.0,4.25
2,2024-08-30,DAX,Germany,38316.88,38323.86,38236.10,38311.46,19307568.0,-0.01
3,2022-07-10,S&P 500,USA,14066.68,14599.10,13969.65,NaN,7663563.0,2.35
4,2020-08-07,SSE Composite,China,37095.64,37457.27,37063.21,37424.57,26746244.0,0.89
5,2021-02-17,DAX,Germany,3267.97,3839.23,3058.38,3620.10,38402743.0,10.78
6,2024-09-08,Hang Seng,Hong Kong,37528.83,37609.32,37301.76,37357.78,48898241.0,-0.46
7,2024-07-29,SSE Composite,China,35199.12,35443.22,34575.45,34861.34,13918195.0,-0.96
8,2020-05-28,DAX,Germany,13091.33,13663.44,12889.42,13403.29,1384083.0,2.38
9,2021-12-17,KSE 100,Pakistan,37530.94,37624.07,37296.41,37374.91,44641889.0,-0.42

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19184 entries, 0 to 19183
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  18600 non-null  object
 1   Index_Name            18600 non-null  object
 2   Country               18600 non-null  object
 3   Open                  18600 non-null  float64
 4   High                  18600 non-null  float64
 5   Low                   18600 non-null  float64
 6   Close                 18227 non-null  float64
 7   Volume                18612 non-null  object
 8   Daily_Change_Percent  18600 non-null  float64
dtypes: float64(5), object(4)
memory usage: 1.3+ MB

In [36]:
df.describe()

,Open,High,Low,Close,Daily_Change_Percent
count,18600.000000,18600.000000,18600.000000,18227.000000,18600.000000
mean,20418.279065,20693.840371,20142.147662,20402.392383,0.008132
std,11270.523366,11273.450600,11271.669659,11280.174953,4.506967
min,1000.650000,1018.520000,349.960000,622.950000,-44.320000
25%,10705.162500,10980.402500,10434.482500,10692.930000,-1.250000
50%,20347.925000,20616.165000,20070.645000,20299.400000,-0.010000
75%,30227.192500,30493.452500,29960.352500,30206.335000,1.230000
max,39988.600000,40680.180000,39985.490000,40474.780000,45.690000

In [37]:
df.describe()

,Open,High,Low,Close,Daily_Change_Percent
count,18600.000000,18600.000000,18600.000000,18227.000000,18600.000000
mean,20418.279065,20693.840371,20142.147662,20402.392383,0.008132
std,11270.523366,11273.450600,11271.669659,11280.174953,4.506967
min,1000.650000,1018.520000,349.960000,622.950000,-44.320000
25%,10705.162500,10980.402500,10434.482500,10692.930000,-1.250000
50%,20347.925000,20616.165000,20070.645000,20299.400000,-0.010000
75%,30227.192500,30493.452500,29960.352500,30206.335000,1.230000
max,39988.600000,40680.180000,39985.490000,40474.780000,45.690000

In [38]:
df.shape

(19184, 9)

In [39]:
df.columns

Index(['Date', 'Index_Name', 'Country', 'Open', 'High', 'Low', 'Close',
       'Volume', 'Daily_Change_Percent'],
      dtype='object')

In [40]:
df.isnull()

,Date,Index_Name,Country,Open,High,Low,Close,Volume,Daily_Change_Percent
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
19179,False,False,False,False,False,False,False,False,False
19180,False,False,False,False,False,False,False,False,False
19181,False,False,False,False,False,False,False,False,False
19182,False,False,False,False,False,False,False,False,False
19183,False,False,False,False,False,False,False,False,False

In [41]:
df.isnull().sum()

Date                    584
Index_Name              584
Country                 584
Open                    584
High                    584
Low                     584
Close                   957
Volume                  572
Daily_Change_Percent    584
dtype: int64

In [42]:
df.dropna(axis="rows" , how="all")

,Date,Index_Name,Country,Open,High,Low,Close,Volume,Daily_Change_Percent
0,2020-11-15,NASDAQ Composite,USA,11361.46,11934.64,11323.18,11797.26,47514127.0,3.84
1,2021-08-30,FTSE 100,UK,10298.33,10829.50,10194.32,10736.46,1471464.0,4.25
2,2024-08-30,DAX,Germany,38316.88,38323.86,38236.10,38311.46,19307568.0,-0.01
3,2022-07-10,S&P 500,USA,14066.68,14599.10,13969.65,NaN,7663563.0,2.35
4,2020-08-07,SSE Composite,China,37095.64,37457.27,37063.21,37424.57,26746244.0,0.89
...,...,...,...,...,...,...,...,...,...
19179,2022-07-26,Dow Jones,USA,23164.70,23892.67,23037.70,23595.56,28096476.0,1.86
19180,2021-12-30,NASDAQ Composite,USA,32881.12,33099.99,32397.70,32414.65,35073989.0,-1.42
19181,2024-11-07,SSE Composite,China,17572.11,17808.43,17047.40,17330.62,29478663.0,-1.37
19182,2021-12-30,FTSE 100,UK,10938.24,10980.35,10799.88,10940.01,8940885.0,0.02
19183,2024-11-02,FTSE 100,UK,5549.21,5703.43,5322.16,5590.65,20082696.0,0.75

In [43]:
df.dropna(axis="rows" , how="all",inplace=True)

In [44]:
df.shape

(18612, 9)

In [45]:
df.dropna(axis="columns",how="all",inplace=True)

In [46]:
df.shape

(18612, 9)

In [47]:
numeric_cols=["Open","High","Low","Close","Volume","Daily_Change_Percent"]

In [48]:
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [49]:
df = df[df["Country"].str.strip() != ""]

In [50]:
df.fillna(method="ffill",axis="rows",inplace=True)

/tmp/ipykernel_20688/3724949672.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill",axis="rows",inplace=True)

In [51]:
df.fillna(method="bfill",axis="rows",inplace=True)

/tmp/ipykernel_20688/2192939287.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill",axis="rows",inplace=True)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18612 entries, 0 to 19183
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  18612 non-null  object
 1   Index_Name            18612 non-null  object
 2   Country               18612 non-null  object
 3   Open                  18612 non-null  float64
 4   High                  18612 non-null  float64
 5   Low                   18612 non-null  float64
 6   Close                 18612 non-null  float64
 7   Volume                18612 non-null  float64
 8   Daily_Change_Percent  18612 non-null  float64
dtypes: float64(6), object(3)
memory usage: 1.4+ MB

In [53]:
df.isnull().sum()

Date                    0
Index_Name              0
Country                 0
Open                    0
High                    0
Low                     0
Close                   0
Volume                  0
Daily_Change_Percent    0
dtype: int64

In [54]:
df.drop_duplicates(inplace=True)

In [55]:
df["Date"]=pd.to_datetime(df["Date"])

In [56]:
df["Country"]=df["Country"].str.capitalize()

In [57]:
df

,Date,Index_Name,Country,Open,High,Low,Close,Volume,Daily_Change_Percent
0,2020-11-15,NASDAQ Composite,Usa,11361.46,11934.64,11323.18,11797.26,47514127.0,3.84
1,2021-08-30,FTSE 100,Uk,10298.33,10829.50,10194.32,10736.46,1471464.0,4.25
2,2024-08-30,DAX,Germany,38316.88,38323.86,38236.10,38311.46,19307568.0,-0.01
3,2022-07-10,S&P 500,Usa,14066.68,14599.10,13969.65,38311.46,7663563.0,2.35
4,2020-08-07,SSE Composite,China,37095.64,37457.27,37063.21,37424.57,26746244.0,0.89
...,...,...,...,...,...,...,...,...,...
19178,2022-10-17,NASDAQ Composite,Usa,10786.27,11052.66,10681.17,10949.12,43691278.0,1.51
19179,2022-07-26,Dow Jones,Usa,23164.70,23892.67,23037.70,23595.56,28096476.0,1.86
19180,2021-12-30,NASDAQ Composite,Usa,32881.12,33099.99,32397.70,32414.65,35073989.0,-1.42
19181,2024-11-07,SSE Composite,China,17572.11,17808.43,17047.40,17330.62,29478663.0,-1.37
19183,2024-11-02,FTSE 100,Uk,5549.21,5703.43,5322.16,5590.65,20082696.0,0.75

In [58]:
df = df[df["Date"].notna()]
df = df[df["Index_Name"].notna()]

In [59]:
df.rename(columns={"Date":"Date_of_investing"},inplace=True)

In [60]:
df.to_csv("cleaned_dataset1.csv",index=False)

## Data Visualisation

In [62]:
df.head()

,Date_of_investing,Index_Name,Country,Open,High,Low,Close,Volume,Daily_Change_Percent
0,2020-11-15,NASDAQ Composite,Usa,11361.46,11934.64,11323.18,11797.26,47514127.0,3.84
1,2021-08-30,FTSE 100,Uk,10298.33,10829.50,10194.32,10736.46,1471464.0,4.25
2,2024-08-30,DAX,Germany,38316.88,38323.86,38236.10,38311.46,19307568.0,-0.01
3,2022-07-10,S&P 500,Usa,14066.68,14599.10,13969.65,38311.46,7663563.0,2.35
4,2020-08-07,SSE Composite,China,37095.64,37457.27,37063.21,37424.57,26746244.0,0.89

In [63]:
import matplotlib.pyplot as plt